/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package lastproject;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
/**
 *
 * @author ZAN
 */
public class Form extends javax.swing.JFrame {

    /**
     * Creates new form Form
     */
    public Form() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Title1 = new javax.swing.JLabel();
        Title2 = new javax.swing.JLabel();
        Title3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btnYa = new javax.swing.JButton();
        btnTidak = new javax.swing.JButton();
        Titlep1 = new javax.swing.JLabel();
        Titlep2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 204, 153));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204), 5));
        jPanel1.setForeground(new java.awt.Color(30, 30, 30));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Title1.setFont(new java.awt.Font("Showcard Gothic", 2, 24)); // NOI18N
        Title1.setForeground(new java.awt.Color(0, 0, 0));
        Title1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Title1.setText("KHAS   SUMENEP");
        jPanel1.add(Title1, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 113, 297, -1));

        Title2.setFont(new java.awt.Font("Showcard Gothic", 2, 24)); // NOI18N
        Title2.setForeground(new java.awt.Color(0, 0, 0));
        Title2.setText("SPESIALIS BUMBU HITAM");
        jPanel1.add(Title2, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 76, 297, -1));

        Title3.setFont(new java.awt.Font("Showcard Gothic", 2, 24)); // NOI18N
        Title3.setForeground(new java.awt.Color(0, 0, 0));
        Title3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Title3.setText("waroenk   pak SUNGUT");
        jPanel1.add(Title3, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 39, 297, -1));

        jPanel2.setBackground(new java.awt.Color(255, 153, 51));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204), 5));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnYa.setBackground(new java.awt.Color(51, 204, 0));
        btnYa.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        btnYa.setText("YA");
        btnYa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnYaActionPerformed(evt);
            }
        });
        jPanel2.add(btnYa, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 100, 177, 57));

        btnTidak.setBackground(new java.awt.Color(255, 51, 51));
        btnTidak.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        btnTidak.setText("TIDAK");
        btnTidak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTidakActionPerformed(evt);
            }
        });
        jPanel2.add(btnTidak, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 177, 57));

        Titlep1.setFont(new java.awt.Font("Showcard Gothic", 2, 24)); // NOI18N
        Titlep1.setText("INGIN MEMESAN ?");
        jPanel2.add(Titlep1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 50, 212, -1));

        Titlep2.setFont(new java.awt.Font("Showcard Gothic", 2, 24)); // NOI18N
        Titlep2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Titlep2.setText("APAKAH ANDA ");
        jPanel2.add(Titlep2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 198, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, 410, 180));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lastproject/img/store_4717749.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 50, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 407, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnYaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnYaActionPerformed
    ImageIcon konf = new ImageIcon(getClass().getResource("img/cheff.png"));
        JOptionPane.showMessageDialog(this,"Selamat datang di waroenk pak Sungut","WELCOME!!!!!", JOptionPane.INFORMATION_MESSAGE,konf);
    this.dispose();
    Entry frame = new Entry();
    frame.setVisible(true); 
    }//GEN-LAST:event_btnYaActionPerformed

    private void btnTidakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTidakActionPerformed
    ImageIcon konf = new ImageIcon(getClass().getResource("img/cheff.png"));
    ImageIcon mks = new ImageIcon(getClass().getResource("img/thanks.png"));
    
    int opsi = JOptionPane.showConfirmDialog(this, "ANDA YAKIN TIDAK INGIN MEMESAN TERLEBIH DAHULU ?", "KONFIRMASI", JOptionPane.YES_NO_OPTION, JOptionPane.INFORMATION_MESSAGE, konf);

    if (opsi == JOptionPane.YES_OPTION || opsi == JOptionPane.CLOSED_OPTION) {
        JOptionPane.showMessageDialog(this, "TERIMAKASIH ANDA TELAH MAMPIR KE WAROENK PAK KUMIS", "TERIMAKASIH", JOptionPane.INFORMATION_MESSAGE, mks);
         System.exit(0);
    }     
    }//GEN-LAST:event_btnTidakActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Form().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Title1;
    private javax.swing.JLabel Title2;
    private javax.swing.JLabel Title3;
    private javax.swing.JLabel Titlep1;
    private javax.swing.JLabel Titlep2;
    private javax.swing.JButton btnTidak;
    private javax.swing.JButton btnYa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
